
groq.api.key=${GROQ_API_KEY}
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
logging.level.org.springframework.ai=DEBUG

spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.6
spring.ai.openai.chat.options.max-tokens=1000